name: Cron Job

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:  

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Visit URL
        run: curl -s https://blogi-doa6.onrender.com
